### ISSUE TITLE
Enemy (melee) deals inconsistent damage

### ISSUE THREAD

**Issue by zdayscott** [zdayscott/Legacy#51]
Depending on a lot of factors, the enemy either hits the player or doesn't.
Some factors could include:
- Whether the player is moving
- If the player was hit last attack (possibly)
- If there are enemies within the attack collider

**Comment by bduinkerk** [comment]
- Damage is not dealt if both are not moving
- Boss is too big to fit through door

**Comment by ErnestoAlvarado** [comment]
Updated the player prefab and he now can take and deal damage while standing still.
